import React from "react";

function ServiceCategory({ handler, serviceValue }) {
  const serviceCategories = [
    "Web Development",
    "Frontend Development",
    "Backend Development",
    "Full Stack Development",
    "Mobile App Development",
    "Cross Platform App Development",
    "iOS App Development",
    "Android App Development",
    "Software Development",
    "Desktop Application Development",
    "Game Development",
    "AI Development",
    "Machine Learning",
    "Data Science",
    "Blockchain Development",
    "Cloud Computing",
    "DevOps",
    "Cyber Security",
    "IT Support",
    "Technical Support",
    "Network Setup",
    "Database Development",
    "API Development",
    "Website Maintenance",
    "Website Migration",
    "WordPress Development",
    "Shopify Development",
    "E-commerce Development",
    "CMS Development",
    "UI/UX Design",
    "Web Design",
    "Graphic Design",
    "Logo Design",
    "Brand Identity Design",
    "Print Design",
    "Packaging Design",
    "Illustration",
    "Animation",
    "Motion Graphics",
    "3D Modeling",
    "3D Rendering",
    "Video Editing",
    "Videography",
    "Photography",
    "Drone Photography",
    "Wedding Photography",
    "Product Photography",
    "Photo Editing",
    "Audio Editing",
    "Music Production",
    "Voice Over",
    "Podcast Editing",
    "Digital Marketing",
    "Social Media Marketing",
    "Search Engine Optimization (SEO)",
    "Search Engine Marketing (SEM)",
    "Email Marketing",
    "Content Marketing",
    "Influencer Marketing",
    "Affiliate Marketing",
    "Marketing Strategy",
    "Brand Management",
    "Content Writing",
    "Copywriting",
    "Technical Writing",
    "Ghostwriting",
    "Blog Writing",
    "Script Writing",
    "Translation",
    "Transcription",
    "Proofreading",
    "Editing",
    "Resume Writing",
    "Virtual Assistant",
    "Customer Support",
    "Data Entry",
    "Data Analysis",
    "Business Consulting",
    "Financial Consulting",
    "Accounting",
    "Bookkeeping",
    "Tax Consulting",
    "Legal Services",
    "Human Resources",
    "Recruitment",
    "Project Management",
    "Event Planning",
    "Travel Planning",
    "Interior Design",
    "Architecture",
    "Real Estate Services",
    "Cleaning Services",
    "Home Repair",
    "Electrical Services",
    "Plumbing Services",
    "Painting Services",
    "Carpentry",
    "Landscaping",
    "Fitness Coaching",
    "Personal Training",
    "Nutrition Consulting",
    "Health Coaching",
    "Online Tutoring",
    "Language Tutoring",
    "Career Coaching",
    "Life Coaching",
    "Counseling",
    "Pet Care",
    "Child Care",
    "Delivery Services",
    "Courier Services",
    "Printing Services",
    "Printing & Publishing",
    "Research Services",
    "Survey Services",
    "Quality Assurance",
    "Product Management",
  ];
  return (
    <select
      name="serviceCategory"
      id="serviceCategory"
      value={serviceValue}
      onChange={handler}
      className="w-full px-4 py-3 rounded-2xl border border-border bg-bg outline-none focus:border-primary"
    >
      <option value="Select">Select your service</option>
      {serviceCategories.map((category) => (
        <option key={category} value={category}>
          {category}
        </option>
      ))}
    </select>
  );
}

export default ServiceCategory;
